CPPFLAGS=-ansi -g -O0 -c
LDFLAGS=-ansi -g -O0 

clean: ; rm -rf WarSimulator;
KingdomPrint: GreatHouse.cpp NobleHouse.cpp Kingdom.cpp Wizard.cpp Whitewalker.cpp Wildling.cpp Enums.cpp Character.cpp War.cpp mainKingdomPrint.cpp; g++ $(LDFLAGS) mainKingdomPrint.cpp GreatHouse.cpp NobleHouse.cpp Kingdom.cpp Wizard.cpp Whitewalker.cpp Wildling.cpp Enums.cpp Character.cpp War.cpp -o WarSimulator
Regression: GreatHouse.cpp NobleHouse.cpp Kingdom.cpp Wizard.cpp Whitewalker.cpp Wildling.cpp Enums.cpp Character.cpp War.cpp mainRegression.cpp; g++ $(LDFLAGS) mainRegression.cpp GreatHouse.cpp NobleHouse.cpp Kingdom.cpp Wizard.cpp Whitewalker.cpp Wildling.cpp Enums.cpp Character.cpp War.cpp -o WarSimulator
Memory: GreatHouse.cpp NobleHouse.cpp Kingdom.cpp Wizard.cpp Whitewalker.cpp Wildling.cpp Enums.cpp Character.cpp War.cpp mainMemory.cpp; g++ $(LDFLAGS) mainMemory.cpp GreatHouse.cpp NobleHouse.cpp Kingdom.cpp Wizard.cpp Whitewalker.cpp Wildling.cpp Enums.cpp Character.cpp War.cpp -o WarSimulator