/*
 * Decompiled with CFR 0_114.
 */
package javax.help.resources;

import java.util.ListResourceBundle;

public class Constants_pl
extends ListResourceBundle {
    public Object[][] getContents() {
        return new Object[][]{{"helpset.wrongPublicID", "Nieznane PublicID {0}"}, {"helpset.wrongTitle", "Pr\u00f3ba ustawienia tytu\u0142u na {0} mimo, \u017ce ma ju \u017c warto\u015b\u0107 {1}."}, {"helpset.wrongHomeID", "Pr\u00f3ba ustawienia homeID na {0} mimo, \u017ce ma ju \u017c warto\u015b\u0107 {1}."}, {"helpset.subHelpSetTrouble", "B\u0142\u0105d w trakcie tworzenia podpomocy: {0}."}, {"helpset.malformedURL", "\u0179le sformu\u0142owany URL: {0}."}, {"helpset.incorrectURL", "Niepoprawny URL: {0}."}, {"helpset.wrongText", "{0} nie mo\u017ce zawiera\u0107 tekstu {1}."}, {"helpset.wrongTopLevel", "{0} nie mo\u017ce by\u0107 znacznikiem najwy\u017cszego poziomu."}, {"helpset.wrongParent", "{1} nie mo\u017ce by\u0107 nadznacznikiem dla {0}."}, {"helpset.unbalanced", "Niezbalansowany znacznik {0}."}, {"helpset.wrongLocale", "Uwaga: atrybut xml:lang {0} jest w konflikcie z domy\u015blnym {1} i domy\u015blnym {2}"}, {"helpset.unknownVersion", "Nieznana wersja {0}."}, {"index.invalidIndexFormat", "Uwaga: Index ma nieprawid\u0142owy format"}, {"index.unknownVersion", "Nieznana wersja {0}."}, {"toc.wrongPublicID", "Nieznany PublicID {0}"}, {"toc.invalidTOCFormat", "Uwaga: TOC ma nieprawid\u0142owy format"}, {"toc.unknownVersion", "Nieznana wersja {0}."}, {"favorites.invalidFavoritesFormat", "Uwaga: Plik Favorites.xml ma nieprawid\u0142owy format"}, {"favorites.unknownVersion", "Nieznana wersja {0}."}, {"map.wrongPublicID", "Nieznane PublicID {0}"}, {"map.invalidMapFormat", "Uwaga: Map ma nieprawid\u0142owy format"}, {"map.unknownVersion", "Nieznana wersja {0}."}, {"index.findLabel", "Znajd\u017a: "}, {"search.findLabel", "Znajd\u017a: "}, {"search.hitDesc", "Liczba wyst\u0105pie\u0144 w dokumencie"}, {"search.qualityDesc", "Miara niedok\u0142adno\u015bci"}, {"search.high", "Najwy\u017csza"}, {"search.midhigh", "Wysoka"}, {"search.mid", "\u015arednia"}, {"search.midlow", "Niska"}, {"search.low", "Najni\u017csza"}, {"favorites.add", "Dodaj"}, {"favorites.remove", "Usu\u0144"}, {"favorites.folder", "Nowy folder"}, {"favorites.name", "Nazwa"}, {"favorites.cut", "Wytnij"}, {"favorites.paste", "Wklej"}, {"favorites.copy", "Kopiuj"}, {"history.homePage", "Strona domowa"}, {"history.unknownTitle", "<nieznany tytu\u0142 strony>"}, {"tooltip.BackAction", "Poprzednia strona"}, {"tooltip.ForwardAction", "Nast\u0119pna strona"}, {"tooltip.PrintAction", "Drukuj"}, {"tooltip.PrintSetupAction", "Ustawienia strony"}, {"tooltip.ReloadAction", "Prze\u0142aduj"}, {"tooltip.FavoritesAction", "Dodaj do ulubionych"}, {"tooltip.HomeAction", "Id\u017a do strony domowej"}, {"access.BackAction", "Do ty\u0142u"}, {"access.ForwardAction", "Nast\u0119pny"}, {"access.HistoryAction", "Historia"}, {"access.PrintAction", "Drukuj"}, {"access.PrintSetupAction", "Ustawienia stron"}, {"access.ReloadAction", "Prze\u0142aduj"}, {"access.HomeAction", "Strona domowa"}, {"access.FavoritesAction", "Dodaj do ulubionych"}, {"access.contentViewer", "Przegl\u0105darka zawarto\u015bci"}};
    }
}

